#!/usr/bin/env python3
"""
Mirror every colour in the page into Display-P3, scaled for vibrancy.

"Scaled" here means the sRGB components are re-read against P3's wider primaries:
#7c3aed (0.486 0.227 0.929) becomes color(display-p3 0.486 0.227 0.929), which is a
more saturated purple because those coordinates now address a bigger gamut. Hues hold,
chroma opens up, neutrals stay put (a grey has equal components in either space).

Nothing is replaced — every rule carrying a colour is DUPLICATED inside
`@media (color-gamut: p3)`, so sRGB displays keep the original values and only P3
displays take the override.

    python3 build_p3.py fontchooserchooser.html
"""
import re, sys

HEX = re.compile(r"#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})\b")
RGBA = re.compile(r"rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+)\s*)?\)")


def hex_to_p3(m: re.Match) -> str:
    h = m.group(1)
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
    return f"color(display-p3 {r:.4f} {g:.4f} {b:.4f})"


def rgba_to_p3(m: re.Match) -> str:
    r, g, b = (float(m.group(i)) / 255 for i in (1, 2, 3))
    a = m.group(4)
    alpha = f" / {a}" if a is not None and float(a) < 1 else ""
    return f"color(display-p3 {r:.4f} {g:.4f} {b:.4f}{alpha})"


def to_p3(css: str) -> str:
    return RGBA.sub(rgba_to_p3, HEX.sub(hex_to_p3, css))


def has_colour(block: str) -> bool:
    return bool(HEX.search(block) or RGBA.search(block))


def split_rules(css: str):
    """Yield (selector, body) for top-level rules, keeping @media/@keyframes whole."""
    out, depth, start = [], 0, 0
    for i, ch in enumerate(css):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                out.append(css[start:i + 1])
                start = i + 1
    return [r.strip() for r in out if r.strip()]


def main(path: str) -> None:
    html = open(path).read()

    # Strip any block this script wrote before, so re-running replaces rather than
    # stacks. The marker is the comment header emitted below.
    marker = "/* ── Display-P3, scaled"
    if marker in html:
        i = html.index(marker)
        d, j = 0, html.index("{", i)
        for k in range(j, len(html)):
            if html[k] == "{":
                d += 1
            elif html[k] == "}":
                d -= 1
                if d == 0:
                    break
        html = html[:i] + html[k + 1:]

    # The page has two <style> blocks: the design system, then the embedded @font-face
    # rules. Only the first carries colour.
    start = html.index("<style>")
    end = html.index("</style>", start)
    css = html[start + len("<style>"):end]

    mirrored = []
    for rule in split_rules(css):
        if not has_colour(rule):
            continue
        # @property has no colours worth mirroring and cannot be redeclared.
        if rule.startswith("@property") or rule.startswith("@font-face"):
            continue
        mirrored.append(to_p3(rule))

    if not mirrored:
        print("no colour rules found")
        return

    block = ("\n\n/* ── Display-P3, scaled ──────────────────────────────────────────────\n"
             "   Same component values re-read against P3's wider primaries: hues hold,\n"
             "   chroma opens up, neutrals are unchanged. sRGB displays never see this\n"
             "   block, so the values above remain the fallback.\n"
             "   Generated by build_p3.py — do not hand-edit. */\n"
             "@media (color-gamut: p3) {\n"
             + "\n".join("  " + r.replace("\n", "\n  ") for r in mirrored)
             + "\n}\n")

    html = html[:end] + block + html[end:]
    open(path, "w").write(html)
    print(f"mirrored {len(mirrored)} rules into P3  |  page {len(html)/1e6:.2f}MB")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "fontchooserchooser.html")
